### PR TITLE
Add massUnwrap

### LINKED ISSUE #4: Add massUnwrap method

### PR DESCRIPTION
**Pull request by tjmehta**
added `shimmer.massUnwrap` w/ tests and docs fixes #4

### CODE REVIEW

**Comment by tjmehta** [comment]
@othiym23 this should be good to pull. lmk

**Comment by overlookmotel** [comment]
I think this PR can be closed now?

**Comment by tjmehta** [comment]
looks like this was pulled in with 15d2f3dd8c5804831e1c98a6d67ba3e8b2eb34e8

**Comment by tjmehta** [comment]
Thanks!

**Pull request closed without merging**
